<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>AstraView.ThumbnailWorker</AssemblyName>
    <RootNamespace>AstraView.ThumbnailWorker</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishSingleFile>false</PublishSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\StarImageViewer.Core\StarImageViewer.Core.csproj" />
  </ItemGroup>
</Project>
