<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <SatelliteResourceLanguages>zh-Hans;en</SatelliteResourceLanguages>
    <AssemblyName>AstraView</AssemblyName>
    <ApplicationIcon>astraview.ico</ApplicationIcon>
    <AssemblyTitle>AstraView</AssemblyTitle>
    <Product>AstraView</Product>
    <Company>AstraView</Company>
    <Version>1.3.3</Version>
    <FileVersion>1.3.3.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="astraview.ico" />
    <Resource Include="astraview-header.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\StarImageViewer.Core\StarImageViewer.Core.csproj" />
  </ItemGroup>
</Project>
