<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>AstraView</AssemblyName>
    <ApplicationIcon>astraview.ico</ApplicationIcon>
    <AssemblyTitle>AstraView</AssemblyTitle>
    <Product>AstraView</Product>
    <Company>AstraView</Company>
    <Version>1.1.1</Version>
    <FileVersion>1.1.1.0</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="astraview.ico" />
    <Resource Include="astraview-header.png" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\StarImageViewer.Core\StarImageViewer.Core.csproj" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
</Project>
